yarnPath: .yarn/releases/yarn-3.2.1.cjs

npmRegistries:
  //europe-npm.pkg.dev/yanzi-1143/yanzi-npm/:
    npmAlwaysAuth: true
    npmAuthToken: "${ARTIFACT_REGISTRY_TOKEN:-}"

npmScopes:
  altacogni:
    npmRegistryServer: "https://europe-npm.pkg.dev/yanzi-1143/yanzi-npm/"
  yanzi:
    npmRegistryServer: "https://europe-npm.pkg.dev/yanzi-1143/yanzi-npm/"
  yanzi-brands:
    npmRegistryServer: "https://europe-npm.pkg.dev/yanzi-1143/yanzi-npm/"